#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:12
#EXT-X-PLAYLIST-TYPE:EVENT
#EXTINF:9.8,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_0.ts
#EXTINF:9.6,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_1.ts
#EXTINF:9.56,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_2.ts
#EXTINF:9.6,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_3.ts
#EXTINF:9.96,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_4.ts
#EXTINF:9.6,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_5.ts
#EXTINF:10.4,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_6.ts
#EXTINF:2.904,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/all.mp4/media_7.ts
#EXTINF:2.861,
#EXT-X-DISCONTINUITY
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_ii/kamil-1024.mp4/media_0.ts
#EXTINF:12,
#EXT-X-DISCONTINUITY
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_iii/all-1024.mp4/media_0.ts
#EXTINF:1.981,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_iii/all-1024.mp4/media_1.ts
#EXT-X-ENDLIST