#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:12
#EXT-X-PLAYLIST-TYPE:EVENT
#EXTINF:12,
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/100.mp4/media_0.ts
#EXTINF:12,
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/100.mp4/media_1.ts
#EXTINF:12,
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/100.mp4/media_2.ts
#EXTINF:12,
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/100.mp4/media_3.ts
#EXTINF:12,
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/100.mp4/media_4.ts
#EXTINF:11.51,
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_i/100.mp4/media_5.ts
{{ $nameChunk }}
#EXTINF:10.8,
#EXT-X-DISCONTINUITY
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_iii/100.mp4/media_0.ts
#EXTINF:3.48,
//montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_iii/100.mp4/media_1.ts
#EXT-X-ENDLIST