#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:12
#EXT-X-PLAYLIST-TYPE:EVENT
#EXTINF:6.933,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_ix/{{ $color }}%20%281280xauto%29.mp4/media_0.ts
#EXTINF:9.72,
#EXT-X-DISCONTINUITY
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_x/all.mp4/media_0.ts
#EXTINF:9.6,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_x/all.mp4/media_1.ts
#EXTINF:10.44,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_x/all.mp4/media_2.ts
#EXTINF:9.6,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_x/all.mp4/media_3.ts
#EXTINF:1.344,
https://montage-vod-hls.cdnvideo.ru/montage-vod/_definst_/mp4:montage/kinder/part_x/all.mp4/media_4.ts
#EXT-X-ENDLIST